server:
  port: 9099
spring:
  application:
    name: "JobSearch"
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: zer0icemax@gmail.com
    password: xazs yxaj muhy wdpm
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com


  datasource:
    url: jdbc:h2:./db/jobSearch;AUTO_SERVER=TRUE
    username: maksat
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

logging:
  level:
    root: error
    org:
      hibernate:
        type: error
        stat: error
      springframework:
        security: debug
    web: info
    sql: error

  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
