server:
  port: 9098
spring:
  application:
    name: "JobSearch"
  datasource:
    url: jdbc:h2:./db/jobSearch;AUTO_SERVER=TRUE
    username: maksat
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml